### ISSUE TITLE
How production ready is this?

### ISSUE THREAD

**Issue by joshuarobs** [nerdsupremacist/Graphaello#19]
I'm wondering how production ready this library is? And if not, what other features would be required to be added in until it becomes production ready? Also is there a specific timeframe for this?

**Comment by nerdsupremacist** [comment]
That's a good question...

**Comment by nerdsupremacist** [comment]
Very good question.

My main concern is that the generated code still might not compile under specific circumstances.

However, I'd argue that since the bugs from this tool occur during development and are very clear to you, that it's ok to use this in production, it won't introduce any bugs in your app, it might just be a bit of a pain in the a** if you happen to find a weird edge case I didn't think of.

**Comment by joshuarobs** [comment]
@nerdsupremacist Thanks for the clarification! Also does this have support for subscriptions?

**Comment by nerdsupremacist** [comment]
Subscriptions are not supported, yet.
It’s in the roadmap. 
But since I haven’t seen that many APIs that even support it, it’s not a priority yet

**Comment by scf4** [comment]
Is this project no longer maintained?
