### ISSUE TITLE
Error SwiftSyntax parser library following the tutorial

### ISSUE THREAD

**Issue by nonfungibletunji** [nerdsupremacist/Graphaello#25]
☕️ Extracting APIs + Structs:
❗️ Error Occurred:

SwiftSyntax parser library isn't compatible

Error: Formulae found in multiple taps: 
       * nerdsupremacist/tap/graphaello
       * nerdsupremacist/graphaello/graphaello

**Comment by nonfungibletunji** [comment]
reinstalled home-brew on Big Sur

**Comment by nerdsupremacist** [comment]
Oh yeah. So I had a lot of reports of this error back when the brew formula was building graphaello from source. In that case I couldn't ensure that the version of libSwiftSyntax matched the what was needed by SwiftSyntax, since I have no idea which version of Xcode every user has installed.

So the solution is to build it via GH-Actions once, where I know exactly which version of Xcode is installed, and have the formula download the built artifacts and copy them. I'm actually super proud of how it turned out: https://github.com/nerdsupremacist/Graphaello/blob/develop/.github/workflows/release.yml

I also renamed the tap in case I want to have other things there. Redirects should have handled the old name of the tap, but you added the second tap again. A fix for that would be to run `brew untap nerdsupremacist/graphaello`. But since you reinstalled brew you don't need it anymore
