### ISSUE TITLE
Issue with macro definition

### ISSUE THREAD

**Issue by AF-cgi** [nerdsupremacist/Graphaello#30]
In beta 3 there is a mistake in the #if-macro-statement. The name looks like `GRAPHAELLO_SWIFT_GRAPH_QL__TARGET`. There is on `_` too much.

**Comment by nerdsupremacist** [comment]
Interesting issue. 
Looks like a case of camel casing gone wrong again.

Do you have a test project where I can reproduce this? 

My suspicion this might also be due to a caching issue, because the path building API is really costly to generate, so it's cached just in case. So since this logic changed from beta 2 to beta 3, and you run code generation on the same project, the macro might be out of sync from what Graphaello injects into the project. So if that's the case a simple hardcoded version number we can bump to invalidate the cache of API.swift.stencil will do the trick

**Comment by AF-cgi** [comment]
If I started with a completely empty project, all thinks are fine.

**Comment by nerdsupremacist** [comment]
Cache invalidation is fixed in beta.4
